# Custom Language File for Launcher Customizer

[ejs.app]
title = "블루샐리"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/yd6gxgStc4"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/blue-sally"
supportLink = "https://github.com/mchlauncher/blue-sally/issues"

[ejs.welcome]
welcomeHeader = "블루샐리"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."
